language: elixir
elixir:
  - '1.10'
otp_release:
  - '23.0.2'

env:
  - MIX_ENV=test

cache:
  directories:
    - _build
    - deps

script: mix coveralls.travis

deploy:
  provider: script

  script: scripts/hex.sh
  on:
    tags: true
