FROM elixir:1.13-slim
RUN apt-get update && apt-get upgrade -y inotify-tools
WORKDIR /code
COPY apps apps
COPY config config
COPY mix.exs mix.exs
COPY mix.lock mix.lock
COPY _build _build
COPY deps deps
RUN  mix local.hex --force && mix local.rebar --force  && mix deps.get -y
